/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlreadyCol {
        "lg": number;
        "md": number;
        "rowWidthChanged": (width: number) => Promise<void>;
        "sm": number;
        "xl": number;
        "xs": number;
    }
    interface AlreadyContainer {
    }
    interface AlreadyGrid {
        "baseColumnCount": number;
    }
    interface AlreadyRow {
    }
}
declare global {
    interface HTMLAlreadyColElement extends Components.AlreadyCol, HTMLStencilElement {
    }
    var HTMLAlreadyColElement: {
        prototype: HTMLAlreadyColElement;
        new (): HTMLAlreadyColElement;
    };
    interface HTMLAlreadyContainerElement extends Components.AlreadyContainer, HTMLStencilElement {
    }
    var HTMLAlreadyContainerElement: {
        prototype: HTMLAlreadyContainerElement;
        new (): HTMLAlreadyContainerElement;
    };
    interface HTMLAlreadyGridElement extends Components.AlreadyGrid, HTMLStencilElement {
    }
    var HTMLAlreadyGridElement: {
        prototype: HTMLAlreadyGridElement;
        new (): HTMLAlreadyGridElement;
    };
    interface HTMLAlreadyRowElement extends Components.AlreadyRow, HTMLStencilElement {
    }
    var HTMLAlreadyRowElement: {
        prototype: HTMLAlreadyRowElement;
        new (): HTMLAlreadyRowElement;
    };
    interface HTMLElementTagNameMap {
        "already-col": HTMLAlreadyColElement;
        "already-container": HTMLAlreadyContainerElement;
        "already-grid": HTMLAlreadyGridElement;
        "already-row": HTMLAlreadyRowElement;
    }
}
declare namespace LocalJSX {
    interface AlreadyCol {
        "lg"?: number;
        "md"?: number;
        "sm"?: number;
        "xl"?: number;
        "xs"?: number;
    }
    interface AlreadyContainer {
    }
    interface AlreadyGrid {
        "baseColumnCount"?: number;
    }
    interface AlreadyRow {
    }
    interface IntrinsicElements {
        "already-col": AlreadyCol;
        "already-container": AlreadyContainer;
        "already-grid": AlreadyGrid;
        "already-row": AlreadyRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "already-col": LocalJSX.AlreadyCol & JSXBase.HTMLAttributes<HTMLAlreadyColElement>;
            "already-container": LocalJSX.AlreadyContainer & JSXBase.HTMLAttributes<HTMLAlreadyContainerElement>;
            "already-grid": LocalJSX.AlreadyGrid & JSXBase.HTMLAttributes<HTMLAlreadyGridElement>;
            "already-row": LocalJSX.AlreadyRow & JSXBase.HTMLAttributes<HTMLAlreadyRowElement>;
        }
    }
}
