/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlreadyButton {
    }
    interface AlreadyCard {
    }
    interface AlreadyCol {
        "lg": number;
        "md": number;
        "rowWidthChanged": (width: number) => Promise<void>;
        "sm": number;
        "xl": number;
        "xs": number;
        "xxl": number;
    }
    interface AlreadyContainer {
    }
    interface AlreadyGrid {
        "baseColumnCount": number;
    }
    interface AlreadyMarkdown {
        "src": string;
    }
    interface AlreadyRow {
    }
}
declare global {
    interface HTMLAlreadyButtonElement extends Components.AlreadyButton, HTMLStencilElement {
    }
    var HTMLAlreadyButtonElement: {
        prototype: HTMLAlreadyButtonElement;
        new (): HTMLAlreadyButtonElement;
    };
    interface HTMLAlreadyCardElement extends Components.AlreadyCard, HTMLStencilElement {
    }
    var HTMLAlreadyCardElement: {
        prototype: HTMLAlreadyCardElement;
        new (): HTMLAlreadyCardElement;
    };
    interface HTMLAlreadyColElement extends Components.AlreadyCol, HTMLStencilElement {
    }
    var HTMLAlreadyColElement: {
        prototype: HTMLAlreadyColElement;
        new (): HTMLAlreadyColElement;
    };
    interface HTMLAlreadyContainerElement extends Components.AlreadyContainer, HTMLStencilElement {
    }
    var HTMLAlreadyContainerElement: {
        prototype: HTMLAlreadyContainerElement;
        new (): HTMLAlreadyContainerElement;
    };
    interface HTMLAlreadyGridElement extends Components.AlreadyGrid, HTMLStencilElement {
    }
    var HTMLAlreadyGridElement: {
        prototype: HTMLAlreadyGridElement;
        new (): HTMLAlreadyGridElement;
    };
    interface HTMLAlreadyMarkdownElement extends Components.AlreadyMarkdown, HTMLStencilElement {
    }
    var HTMLAlreadyMarkdownElement: {
        prototype: HTMLAlreadyMarkdownElement;
        new (): HTMLAlreadyMarkdownElement;
    };
    interface HTMLAlreadyRowElement extends Components.AlreadyRow, HTMLStencilElement {
    }
    var HTMLAlreadyRowElement: {
        prototype: HTMLAlreadyRowElement;
        new (): HTMLAlreadyRowElement;
    };
    interface HTMLElementTagNameMap {
        "already-button": HTMLAlreadyButtonElement;
        "already-card": HTMLAlreadyCardElement;
        "already-col": HTMLAlreadyColElement;
        "already-container": HTMLAlreadyContainerElement;
        "already-grid": HTMLAlreadyGridElement;
        "already-markdown": HTMLAlreadyMarkdownElement;
        "already-row": HTMLAlreadyRowElement;
    }
}
declare namespace LocalJSX {
    interface AlreadyButton {
    }
    interface AlreadyCard {
    }
    interface AlreadyCol {
        "lg"?: number;
        "md"?: number;
        "sm"?: number;
        "xl"?: number;
        "xs"?: number;
        "xxl"?: number;
    }
    interface AlreadyContainer {
    }
    interface AlreadyGrid {
        "baseColumnCount"?: number;
    }
    interface AlreadyMarkdown {
        "src"?: string;
    }
    interface AlreadyRow {
    }
    interface IntrinsicElements {
        "already-button": AlreadyButton;
        "already-card": AlreadyCard;
        "already-col": AlreadyCol;
        "already-container": AlreadyContainer;
        "already-grid": AlreadyGrid;
        "already-markdown": AlreadyMarkdown;
        "already-row": AlreadyRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "already-button": LocalJSX.AlreadyButton & JSXBase.HTMLAttributes<HTMLAlreadyButtonElement>;
            "already-card": LocalJSX.AlreadyCard & JSXBase.HTMLAttributes<HTMLAlreadyCardElement>;
            "already-col": LocalJSX.AlreadyCol & JSXBase.HTMLAttributes<HTMLAlreadyColElement>;
            "already-container": LocalJSX.AlreadyContainer & JSXBase.HTMLAttributes<HTMLAlreadyContainerElement>;
            "already-grid": LocalJSX.AlreadyGrid & JSXBase.HTMLAttributes<HTMLAlreadyGridElement>;
            "already-markdown": LocalJSX.AlreadyMarkdown & JSXBase.HTMLAttributes<HTMLAlreadyMarkdownElement>;
            "already-row": LocalJSX.AlreadyRow & JSXBase.HTMLAttributes<HTMLAlreadyRowElement>;
        }
    }
}
